name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploying-to-testing:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      #checkout repository
      - name: Code Checkout
        uses: actions/checkout@v4

      # Log in to Docker hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Set the tag as an environment variable
      - name: Set Tag
        id: tag
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build the Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$TAG

      # Push the Docker image
      - name: Push the Docker Image
        run: |
          docker tag my-image-name:$TAG ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
          
